### ISSUE TITLE
能添加支持ingress么？

### ISSUE THREAD

**Issue by piscesmk2013** [cool-delete/CorrectPMcoord#1]
请问能同时支持ingress吗？ingress的偏移也很蛋疼
感谢作者的付出

**Comment by cool-delete** [comment]
尽量试试吧  能写出这个纯属偶然的

**Comment by cool-delete** [comment]
刚试过 不能反编译ingress 看不到源码

**Comment by ghost** [comment]
其实可以用IITC的插件修复(仅限Intel map)
ingress本身的话，一般来说不会飘很远，除非到了无法接近的地方。
